@extends('layouts.app')

@section('title', 'Verification management | MigraVerify')

@section('content')
<section class="min-h-[70vh] bg-slate-50 py-10 sm:py-14">
    <div class="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-bold uppercase tracking-[0.16em] text-sky-700">Admin console</p><h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-950">Verification management</h1><p class="mt-2 text-sm text-slate-600">Upload documents, issue QR verification links, and control access.</p></div><a href="{{ route('home') }}" class="text-sm font-bold text-slate-600 hover:text-sky-700">View public portal</a></div>

        @if (session('success'))<div class="mt-7 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif

        <div class="mt-8 grid gap-5 md:grid-cols-3">
            <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">Total documents</p><p class="mt-3 text-3xl font-bold tracking-tight text-slate-950">{{ \App\Models\VerificationDocument::count() }}</p></div>
            <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">QR scans</p><p class="mt-3 text-3xl font-bold tracking-tight text-sky-700">{{ \App\Models\VerificationDocument::sum('view_count') }}</p></div>
            <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">Site traffic</p><p class="mt-3 text-3xl font-bold tracking-tight text-indigo-700">{{ \App\Models\PageView::count() }}</p></div>
        </div>

        <div class="mt-8 grid gap-8 lg:grid-cols-[.82fr_1.18fr]">
            <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><h2 class="text-lg font-bold text-slate-950">Issue a verification link</h2><p class="mt-1 text-sm leading-6 text-slate-500">The document receives a unique QR reference after upload.</p>
                <form method="POST" action="{{ route('admin.doc.store') }}" enctype="multipart/form-data" class="mt-6 space-y-4">@csrf
                    <div><label for="title" class="block text-sm font-bold text-slate-700">Document title</label><input id="title" name="title" value="{{ old('title') }}" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-4 focus:ring-sky-100">@error('title')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                    <div><label for="applicant_name" class="block text-sm font-bold text-slate-700">Applicant name</label><input id="applicant_name" name="applicant_name" value="{{ old('applicant_name') }}" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-4 focus:ring-sky-100">@error('applicant_name')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                    <div><label for="document_type" class="block text-sm font-bold text-slate-700">Document type</label><select id="document_type" name="document_type" required class="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-4 focus:ring-sky-100"><option value="">Choose a type</option><option value="Marriage certificate">Marriage certificate</option><option value="Work permit">Work permit</option><option value="Residency permit">Residency permit</option><option value="Identity evidence">Identity evidence</option></select>@error('document_type')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                    <div><label for="document" class="block text-sm font-bold text-slate-700">Document file</label><input id="document" type="file" name="document" accept="application/pdf,image/jpeg,image/png" required class="mt-1.5 block w-full rounded-xl border border-slate-200 p-2 text-sm text-slate-600 file:mr-3 file:rounded-lg file:border-0 file:bg-sky-50 file:px-3 file:py-1.5 file:text-sm file:font-bold file:text-sky-700">@error('document')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                    <div><label for="expires_at" class="block text-sm font-bold text-slate-700">Expiry date <span class="font-normal text-slate-400">(optional)</span></label><input id="expires_at" type="datetime-local" name="expires_at" value="{{ old('expires_at') }}" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-4 focus:ring-sky-100">@error('expires_at')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                    <label class="flex items-center gap-2 text-sm font-semibold text-slate-700"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" checked class="h-4 w-4 rounded border-slate-300 text-sky-600 focus:ring-sky-500">Activate verification link now</label>
                    <button type="submit" class="inline-flex w-full justify-center rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white transition hover:bg-sky-700">Upload and issue reference</button>
                </form>
            </div>
            <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-6 sm:p-7"><h2 class="text-lg font-bold text-slate-950">Issued documents</h2><p class="mt-1 text-sm text-slate-500">Manage status and retrieve a document’s QR code.</p></div><div class="overflow-x-auto"><table class="min-w-[700px] w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-bold uppercase tracking-[0.08em] text-slate-500"><tr><th class="px-5 py-4">Document</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Scans</th><th class="px-5 py-4">QR</th><th class="px-5 py-4">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($documents as $doc)<tr><td class="px-5 py-4"><p class="font-bold text-slate-900">{{ $doc->title }}</p><p class="mt-0.5 text-xs text-slate-500">{{ $doc->applicant_name }}</p></td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $doc->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $doc->is_active ? 'Active' : 'Hidden' }}</span></td><td class="px-5 py-4 font-bold text-sky-700">{{ $doc->view_count }}</td><td class="px-5 py-4">{!! \SimpleSoftwareIO\QrCode\Facades\QrCode::size(46)->generate(route('verify.captcha', $doc->uuid)) !!}</td><td class="px-5 py-4"><form action="{{ route('admin.doc.toggle', $doc->id) }}" method="POST">@csrf<button class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 transition hover:border-sky-200 hover:bg-sky-50 hover:text-sky-700">{{ $doc->is_active ? 'Hide' : 'Activate' }}</button></form></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-sm text-slate-500">No documents issued yet.</td></tr>@endforelse</tbody></table></div></div>
        </div>
    </div>
</section>
@endsection
